const fs = require("fs");
const path = require("path");

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function createProjectStructure(mission) {
  const name = slugify(mission.replace(/^build\s+/i, ""));
  const projectDir = path.join(process.cwd(), "projects", name);

  fs.mkdirSync(projectDir, { recursive: true });

  fs.writeFileSync(
    path.join(projectDir, "index.html"),
`<!DOCTYPE html>
<html>
<head>
  <title>${mission}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>${mission}</h1>
  <p>Generated by Rev-9.</p>
  <script src="script.js"></script>
</body>
</html>
`
  );

  fs.writeFileSync(
    path.join(projectDir, "style.css"),
`body {
  font-family: Arial, sans-serif;
  padding: 2rem;
}
`
  );

  fs.writeFileSync(
    path.join(projectDir, "script.js"),
`console.log("Rev-9 project online");
`
  );

  console.log(`Project created: ${projectDir}`);
}

function executeTask(task, mission) {
  switch (task.task) {
    case "Create project structure":
      createProjectStructure(mission);
      break;

    case "Build user interface":
      console.log("Building UI...");
      break;

    case "Generate files or code":
      console.log("Generating files...");
      break;

    case "Audit output for problems":
      console.log("Running audit...");
      break;

    case "Save mission notes":
      console.log("Writing mission memory...");
      break;

    case "Sync changes to GitHub":
      console.log("Preparing GitHub sync...");
      break;

    default:
      console.log(`Working on: ${task.task}`);
  }
}

module.exports = { executeTask };
